CREATE TABLE IF NOT EXISTS cake
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    calories    DECIMAL,
    image       VARCHAR(255),
    price       DECIMAL,
    weight      DECIMAL,
    description VARCHAR(255),
    CONSTRAINT pk_cake PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS composition
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_composition PRIMARY KEY (id)
);

ALTER TABLE composition
    ADD CONSTRAINT uc_composition_name UNIQUE (name);

CREATE TABLE user_info
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number  VARCHAR(255)                            NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    CONSTRAINT pk_user_info PRIMARY KEY (id)
);

ALTER TABLE user_info
    ADD CONSTRAINT uc_user_info_number UNIQUE (number);

CREATE TABLE order_info
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    delivery INTEGER,
    payment  INTEGER,
    status   INTEGER,
    date     date,
    address  VARCHAR(255),
    CONSTRAINT pk_order_info PRIMARY KEY (id)
);

ALTER TABLE order_info
    ADD CONSTRAINT FK_ORDER_INFO_ON_USER FOREIGN KEY (user_id) REFERENCES user_info (id);
CREATE TABLE order_cake
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT                                  NOT NULL,
    cake_id  BIGINT                                  NOT NULL,
    count    INTEGER,
    CONSTRAINT pk_order_cake PRIMARY KEY (id)
);

ALTER TABLE order_cake
    ADD CONSTRAINT FK_ORDER_CAKE_ON_CAKE FOREIGN KEY (cake_id) REFERENCES cake (id);

ALTER TABLE order_cake
    ADD CONSTRAINT FK_ORDER_CAKE_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_info (id);