CREATE TABLE IF NOT EXISTS cake
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    calories    DECIMAL,
    image       VARCHAR(255),
    price       DECIMAL,
    weight      DECIMAL,
    description VARCHAR(255),
    CONSTRAINT pk_cake PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS composition
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_composition PRIMARY KEY (id)
);

ALTER TABLE composition
    ADD CONSTRAINT uc_composition_name UNIQUE (name);